# Site settings
title: AADL
email: jhugues@andrew.cmu.edu
description: > # this means to ignore newlines until "baseurl:"
  SAE AADL Website. Informations on the language, tool support, meeting information.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://aadl.info" # the base hostname & protocol for your site
twitter_username:
github_username:  jjhugues

# Build settings
markdown: kramdown
